### ISSUE TITLE
Make chart example work in Windows

### ISSUE THREAD

**Issue by saroad2** [beeware/toga_chart#8]
At the moment, the example chart doesn't work in Windows:

![chart](https://user-images.githubusercontent.com/19425795/80626397-0a6e2580-8a57-11ea-828b-f2f7bb80a3fa.png)

I'm working on fixing the problem. Most of the work would be in the *Toga* repository which only recently started to support `Canvas` in Windows. If someone wishes to give a hand and help, that would be much appreciated!

**Comment by freakboy3742** [comment]
Completely agreed that there are bugs in this, but can I take a moment for a huge WOOOHOOOO that it gets this far!

**Comment by saroad2** [comment]
Thanks man! 😃

**Comment by saroad2** [comment]
So I made a *little* progress:

![chart](https://user-images.githubusercontent.com/19425795/81108709-b618e900-8f21-11ea-864e-b0da8861318b.png)

But the text is still... not good. I think the reason for that is that the Matplotlib text2path module creates paths that are not closed right in Windows, so it fills it wrongly.

An easy fix would be to use Toga's default text rendering, which as of today works nicely in Windows:

![filled_text](https://user-images.githubusercontent.com/19425795/81108814-d9dc2f00-8f21-11ea-981c-e8455927eec8.png)
(This is taken from the `Canvas` example of Toga)

The downside of this approach is that we won't be able to use LaTeX syntax at the moment until Toga would support it out-of-the-box.

The other option is to investigate how Matplolib creates its paths and figure out a way to create those on our own. It feels like an overstep at the moment, in my opinion.

I really need this feature for windows, so if you ask me -- I would go with the easy solution for now and try to go for the "real" solution in the future. I know it means losing a feature that works fine in Mac, but the positive side of that is that we would have a module that can be used by all platforms.

**Comment by freakboy3742** [comment]
Agreed that the easy solution is completely acceptable for now. Ideally we wouldn't *lose* the implementation we currently have for the platforms where it works, but if that is unavoidable, then working is better than not working.

**Comment by saroad2** [comment]
We are almost there!
![chart](https://user-images.githubusercontent.com/19425795/81647498-c3f4cf80-9435-11ea-82e0-f341bd84fe41.png)

Just need to implement *rotate* and *translate* for `Canvas` in windows -- and we are good to go!

**Comment by freakboy3742** [comment]
As if #9, I'm going to call this done; and I'll open a separate ticket to track the TODO around math rendering for windows.
